TWITTER_KEY: '9ppkRVs7cdFKz2d9nsSg'
TWITTER_SECRET: 'z5eXHcLsaOpPPB8YOsFVLaNSbjIobxahv9y5nfrg'
OAUTH_TOKEN: '1859299015-BEp7ykDcldZ5SwEPGId25z8wLP9CIPJB34tIiff'
OAUTH_TOKEN_SECRET: 'DjrZfYLA15gaDXhbwyGIbStGiEpf06ZXAiUZszAk1o'